### ISSUE TITLE
보고서 작성 restapi 연결

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-fe#13]
**Description**
Swagger 통해 api 명세에 따라 restapi 연결

**Todo**

- [x] react-form-hook 을 통해 state관리
- [x] firebase Storage 연결하여 이미지 스토리지 구축 -> test 모드
- [x] browser-image-compression 라이브러리를 통해 이미지 압축 기능 구현
- [x] api 연결
