### ISSUE TITLE
FEATURE : 권한 설정

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-fe#48]
## Issue Description

각 사용자마다 권한을 부여 함으로써 보여지는 UI를 다르게 하도록 함.
0. NonUser - <비로그인한 유저> Rank , Login 만 가능
1. User - <팀이 없는 로그인한 유저> Login ,  Rank , Profile , Apply
2. Member - <팀이 있는 로그인한 유저> Login , Rank , Profile , myStudy , report
3. Admin - <관리자> Login , Rank , Profile , Manager
 
## Todo
- [x] 로그인 시 권한을 파싱하여 localStorage 저장
- [x] 권한에 맞게 UI 보여지도록 설정
- [x] 권한에 따라 페이지 접근 막기
