### ISSUE TITLE
FIX - MANAER 페이지 버그 수정

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-fe#52]
## Description
관리자 페이지 쪽에 일부 버그를 수정한다.

## Todo
- [x] 로딩이 사라지지 않는 버그
- [ ] api가 잘 작동하지 않는 버그
- [x] ui 문제 ( + 반응형 )
