### ISSUE TITLE
HOTFIX : 서비스 전 긴급 수정 사항

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-fe#65]
## Description
서비스 전 긴급 수정 사항

## Todo
- [x] 과목 이름이 길기에 그에 맞게 테이블의 픽셀을 조절한다.
- [x] 매니저 쪽 보고서 열람 페이지 UI 수정
- [x] 메인 페이지에서 auth API를 통해 토큰/권한 확인
