### ISSUE TITLE
[Request] FIX : 사진 보관함을 Firebase Storage에서 Isel 서버로 migrate 한다.

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-fe#82]
## Request Description

관리자는 사진을 직접 서버에서 관리하기 원한다.
요청 사항에 따라서 현재 Firebase Storage에 업로드 되고 있는 사진을 Isel 서버로 업로드 되도록 migrate한다.

## ToDo
- [x] 이미지 업로드 시 blob으로 미리 보기를 지원한다.
- [x] 작성 글이 업로드 될 때 이미지를 형식 (컨벤션: {연도 (YYYY)}/{학기 (spring | fall)}/group{태그 번호}/{UUID}.{확장자}) 에 맞게 서버에 보낸다.
- [x] 보내기 전 이미지 압축을 진행한다.
